name: Python Pull Request Workflow
on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '19 12 * * 5'
      
jobs:

  qa:
    name: Quality check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
#       - name: Run unit tests
#         run: |
#           pip install pytest
#           pytest
      - name: Wemake Python Stylguide
        uses: wemake-services/wemake-python-styleguide@0.14.1
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
